version: '3.1'

services:

  express-app:
    build: ./express
    ports:
      - "49160:8080"

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME= root
      - MONGO_INITDB_ROOT_PASSWORD= password