version: 2.1

jobs:
  say-hello:
    
    docker:
      - image: cimg/base:stable
    
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  run-docker-compose:

    docker:
      - image: cimg/base:stable
  
    steps:
      - checkout
      - run:
        name: Install Docker Compose
        environment:
          COMPOSE_VERSION: '1.29.2'
        command: |
          curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: "Run the Application on Docker"
          command: "docker-compose up"



workflows:
  test_circle_ci:
    jobs:
      - say-hello
      - run-docker-compose