version: 2.1

jobs:
  say-hello:
    
    docker:
      - image: cimg/base:stable
    
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  run-docker:
    
    docker:
      - image: cimg/base:stable
    
    steps:
      - checkout
      - run:
          name: "Run the Mongodb Docker"
          command: "echo Hello, World!"



workflows:
  Test-Ci/Cd:
    jobs:
      - say-hello
      - run-docker